Adds README
IcaliaLabs/sepomex-form-plugin pull request #4
Opened 2017-12-20 18:17 UTC by ReneSG

What does this PR do?

+ Adds readme explaining how the plugin works.

2017-12-20 19:20 UTC, kurenn requested changes
Remember to add the code of conduct - https://www.contributor-covenant.org/

2017-12-20 19:20 UTC, kurenn commented on README.md
> +  <script type="text/javascript" src="http://maps.googleapis.com/maps/api/js?key=YOUR_API_KEY"></script>
I would suggest you to add a file on how to get an api key or the link from google

2017-12-20 20:41 UTC, ReneSG commented
Done! 😃

2017-12-21 16:08 UTC, kurenn approved these changes

2017-12-21 16:08 UTC, merged